version: '3.7'

services:
  db:
    container_name: fridgify_backend_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend
    ports:
      - 5434:5432
    networks:
      - fridgify_production
  backend:
    container_name: fridgify_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - /home/fridgify/static_files/production/:/fridgify/fridgify_backend/static/
      - /home/fridgify/logs/production/:/fridgify/logs/
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=fridgify_backend.settings.production
    env_file:
      - ${ENV_FILE:-.empty}
    networks:
      - fridgify_production
volumes:
  postgres_data:
networks:
  fridgify_production:
