version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend_dev
  backend:
    build:  .
    ports:
      - 9000:9000
    depends_on:
      - db
volumes:
  postgres_data:
